#!/usr/bin/env python3
"""Generate run-params for all 24 synthetic tasks and merge them into pilot_tasks.json.

For each task: binary + input_method come from its manifest; known_flag from `solve.py --emit`;
success_marker / fail_marker are derived empirically (last stdout line on the real flag / on junk).
Existing non-synthetic entries (ovl_*) and _note are preserved. Idempotent; re-run after any task
rebuild. Run from repo root: python tasks/synthetic/gen_run_params.py
"""
from __future__ import annotations
import json, subprocess
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
BASE = REPO / "tasks/synthetic"
JUNK = "zz_not_a_flag_zz"

def emit(d: Path) -> str:
    return subprocess.run(["python3", str(d / "groundtruth/solve.py"), "--emit"],
                          capture_output=True, text=True).stdout.strip()

def last_line(binp: Path, arg: str, io: str) -> str:
    if io == "stdin":
        p = subprocess.run([str(binp)], input=arg, capture_output=True, text=True, timeout=10)
    else:
        p = subprocess.run([str(binp), arg], capture_output=True, text=True, timeout=10)
    lines = [ln for ln in p.stdout.splitlines() if ln.strip()]
    return lines[-1] if lines else ""

def main() -> int:
    entries = {}
    for d in sorted(p for p in BASE.glob("t_*") if p.is_dir()):
        m = json.load(open(d / "manifest.json"))
        binp = d / m["binary"]; io = m["input_method"]
        real = emit(d)
        success = last_line(binp, real, io)          # real -> accept marker is the final line
        fail = last_line(binp, JUNK, io)             # malformed junk -> fail marker is the final line
        rel = str((d / m["binary"]).relative_to(REPO))
        entries[m["task_id"]] = {
            "binary": rel, "input_method": io,
            "success_marker": success, "fail_marker": fail,
            "known_flag": real,
            "_note": f"synthetic {m['archetype']} ({m['target_w2_subtype']}); run-params generated by gen_run_params.py",
        }
    # merge: preserve non-synthetic (ovl_*) entries + _note; refresh all synthetic (t_*)
    pj = REPO / "pilot_tasks.json"
    existing = json.loads(pj.read_text())
    merged = {}
    for k, v in existing.items():
        if k == "_note" or k.startswith("ovl_") or not k.startswith("t_"):
            merged[k] = v
    merged.update(entries)
    # keep _note first-ish by rebuilding with _note then sorted keys
    note = merged.pop("_note", None)
    out = {}
    if note is not None:
        out["_note"] = note
    for k in sorted(merged):
        out[k] = merged[k]
    pj.write_text(json.dumps(out, indent=2) + "\n")
    print(f"wrote {len(entries)} synthetic entries; total tasks in pilot_tasks.json: {len(out)-1} (+_note)")
    # show a few derived markers for spot-check
    for t in ["t_a_02_decoy_function", "t_d_02_silent_validation", "t_d_04_silent_validation", "t_d_05_silent_validation"]:
        e = entries[t]; print(f"  {t}: success={e['success_marker']!r} fail={e['fail_marker']!r} io={e['input_method']}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
